config/routes.rb
Rails.application.routes.draw do
  # get 'home/index'
  root 'home#index'

  # get 'home/topic'
  post "topic" => 'home#topic'

  post "search" => 'home#search'

  get 'searches/index'
  get 'searches/new'
  get 'searches/create'
  get 'searches/destroy'
  get 'searches/show'

  resources :searches, only: [:index, :new, :create, :destroy, :show]  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord
	validates_uniqueness_of :search_term
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	require 'net/http'
  	require 'json'

  	@url = 'https://newsapi.org/v2/top-headlines?country=us&apiKey=fde93151b2814cd68c8e0396dfda3e32'
  	@uri = URI(@url)
  	@response = Net::HTTP.get(@uri)
  	@output = JSON.parse(@response)
  	# @output = JSON.parse(@response)['articles'][0,5]

  	if @output.empty?
  		@final_output = "Error"
  	elsif !@output
  		@final_output = "Error"
  	else
	  	@final_output = @output['articles']
	  	# @final_output = @output['articles'][0]['source']['id']

	end


  end


	def topic
		@term_query = params[:topic]
		if params[:topic] == ""
			@term_query = "Please enter a topic to search for."
		elsif params[:topic]
			#do api stuff

		  	require 'net/http'
		  	require 'json'

		  	@url = 'https://newsapi.org/v2/top-headlines?country=us&q=' + @term_query + '&apiKey=fde93151b2814cd68c8e0396dfda3e32'
		  	@uri = URI(@url)
		  	@response = Net::HTTP.get(@uri)
		  	@output = JSON.parse(@response)

		  	@req = JSON.parse(@response)['status']

		  	# @req = (request.env).inspect 
		  	# @output = JSON.parse(@response)['articles'][0,5]

		  	if @output.empty?
		  		@final_output = "Error"
		  	elsif !@output
		  		@final_output = "Error"
		  	else
			  	@final_output = @output['articles']
			end



		end
	end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def index
  	@searches = Search.all
  end

  def show
    @search = Search.find(params[:id])
  end

  def new
  end

  def create
  	# render plain: params[:search].inspect
	@search = Search.new(search_params)
	if @search.save
		render :json => @search
	else
		render :json => { :errors =>
			@search.errors.full_messages }, :status => 422
	end
	# redirect_to root_path
  end

  def destroy
  end

  private
  	def search_params
  		params.require(:search).permit(:search_term)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand">Anywhere News</a>

  <%= form_tag topic_path, :method => 'POST' do %>
  <div class="form-inline">
  	<%= text_field_tag 'topic', nil, placeholder: "Search news", class: "form-control mr-sm-2" %>
  	<%= submit_tag 'Search', id: 'topic_submit', class: 'btn btn-outline-success my-2 my-sm-0' %>
  <% end %>
  </div>

<%= form_with scope: :search, id: 'myform', url: searches_path, local: true do |form| %>
<div style="right: -1000px; position: absolute;">
  <p>
    <%= form.label :search_term %><br>
    <%= form.text_area :search_term %>
  </p> 
  <p>
    <%= form.submit id: 'linkid' %>
  </p>
<% end %>
</div>

<script>
	// autofill second search form
	var topic_input = document.getElementById("topic");
	var search_input = document.getElementById("search_search_term");
	topic_input.onblur=function FillSearch() {
	  search_input.value = topic_input.value;
	};
	// autosubmit second search form
	var topic_submit = document.getElementById("topic_submit");
	topic_submit.onmousedown=function ghostsubmit() {
	  document.getElementById("myform").submit();
	};

</script>

<script>
	// submit second form by ajax
    // $(function() {
    //     $("#myform").on("submit", function(e) {
    //         e.preventDefault();
    //         $.ajax({
    //             url: $(this).attr("action"),
    //             type: 'POST',
    //             data: $(this).serialize()
    //         });
    //     });
    // });
</script>


</nav>

app/views/home/index.html.erb
<h1>Anywhere News</h1>
<p>Find me in app/views/home/index.html.erb</p>

<!-- <%= @final_output %> -->

<% @final_output.each do |item| %>
  <ul>
    <li>
    	<%= item['source']['name'] %></br>
    	<%= item['author'] %></br>
	    <%= item['title'] %></br>
	    <%= item['description'] %></br>
	    <%= item['publishedAt'] %>
	</li>
  </ul>
<% end %>

app/views/home/search.html.erb
post search to db

app/views/home/topic.html.erb
Search Results:
</br>
<%= @final_output %>
</br></br>
@term_query is:  
</br>
<%= @term_query %>
</br></br>
Status:
</br>
<%= @req %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newsevent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= render 'home/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/searches/index.html.erb
<h1>Searches#index</h1>
<p>Find me in app/views/searches/index.html.erb</p>


  <% @searches.each do |search| %>
    <tr>
      <td><%= search.search_term %></td>
      <td><%= search.results_count %></td>
      <td><%= link_to 'Show', search_path(search) %></td>
    </tr>
  <% end %>

app/views/searches/new.html.erb
<h1>New Search</h1>